version: "3.0"

services:
  rabbitmq:
    container_name: "skeleton_service_rabbitmq_service"
    image: rabbitmq:3.8-management-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  skeleton_service_service_db:
    container_name: "skeleton_service_db"
    image: postgres:14.1-alpine
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRES_USER=skeleton_service
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skeleton_service
    ports:
      - '5445:5445'
    volumes:
      - skeleton_service_db:/var/lib/postgresql/data
    command: -p 5445
volumes:
  skeleton_service_db:
    driver: local

networks:
  skeleton_network:
    driver: bridge
